version: "3.1"
services:
  postgres:
    container_name: postgres-container
    image: postgres:14.5
    volumes:
      - data:/var/lib/postgresql/data
      - type: bind
        source: ./backend/sql 
        target: /docker-entrypoint-initdb.d
    env_file:
     - ./backend/env/postgres.env
    ports:
      - '5432:5432'
  adminer:
    container_name: postgres-admin-container
    image: adminer
    restart: always
    ports:
      - 8080:8080
  backend:
    container_name: virtual-room-backend-container
    build: ./backend
    image: virtual-room-backend:v1
    ports:
      - '5001:5001'
    env_file:
      - ./backend/env/server.env
    depends_on:
      - postgres
    restart: unless-stopped
  frontend:
    container_name: virtual-room-frontend-container
    build: ./frontend
    image: virtual-room-frontend:v1
    ports: 
      - '3001:3001'
    env_file: 
      - ./frontend/.env
    restart: unless-stopped
volumes:
  data: