# for composing the backend ecosystem - backend server / database / database admin site
version: "3.1"
services:
  postgres:
    image: postgres:14.5
    volumes:
      - data:/var/lib/postgresql/data
      - type: bind
        source: ./sql 
        target: /docker-entrypoint-initdb.d
    env_file:
      - ./env/postgres.env
    ports:
      - '5432:5432'
    container_name: postgres-container
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    container_name: postgres-admin-container
  # backend:
  #   container_name: backend-container
  #   build: .
  #   image: virtual-room-backend:v1
  #   ports:
  #     - '5000:5000'
  #   env_file:
  #     - ./env/server.env
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped

volumes:
  data: